### ISSUE TITLE
Other repo's is calling your https://gpvc.arturio.dev/ API as a refresh page...

### ISSUE THREAD

**Issue by MasterExecuson** [arturssmirnovs/github-profile-views-counter#8]
Hi there... 

I was trying to implement some self hosted counter, but when got to see some examples, saw that some repo's we find call your API a refresh call on the url...

EX: https://turnipguy30.github.io/Celebi/

> <!doctype html>

> html lang="en" dir="ltr">
>   head>
>     **meta charset="utf-8" http-equiv="refresh" content="0; URL=armand-morin.html">**
>     link rel="icon" href="../images/celebi.png">
>     title>armand-morin | Celebi</title>
>     style>@import url("../styles/index.css");</style>
>   /head>
>   body>
>     h1>armand-morin</h1>
>     img src="https://gpvc.arturio.dev/armand-morin">
>   /body>
> /html>

I saw that the number keeps getting up if I stay some time in the site, and thought that you don't have caching on your code. 

Didn't know a lot about that, but maybe this could help with server issues...

**Comment by arturssmirnovs** [comment]
Yes there is no cache as it would prevent counter from going up :) 
Currently workflow is like -> github image (uncached) -> my api
If the github image would be cached my api wouldn't receive request & counter wouldn't go up.
